# Generated by Django 3.0.8 on 2020-08-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
