# Generated by Django 3.0.8 on 2020-09-05 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200828_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='profile_pic',
            new_name='store_pic',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Seller'),
        ),
    ]
