# Generated by Django 3.0.8 on 2020-09-18 21:57

from django.db import migrations, models
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20200910_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='digital',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='seller',
            name='store_pic',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
