# Generated by Django 3.0.8 on 2020-10-04 11:14

from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20200918_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Seller'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='owner_pic',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
