# Generated by Django 3.0.8 on 2020-10-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20201004_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='description_store',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
