# Generated by Django 3.0.8 on 2020-10-26 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20201004_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyWithdrawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False, null=True)),
                ('withdrawl_amount', models.IntegerField(default=0, null=True)),
                ('bank_account_name', models.CharField(max_length=200, null=True)),
                ('bank_account_number', models.IntegerField(null=True)),
                ('bank_name', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='TempAccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_balance', models.IntegerField(default=0)),
                ('available_balance', models.IntegerField(default=0)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Seller')),
                ('withdrawl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.MoneyWithdrawl')),
            ],
        ),
        migrations.CreateModel(
            name='Sellertransc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_balance', models.IntegerField(blank=True, default=0, null=True)),
                ('available_balance', models.IntegerField(blank=True, default=0, null=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Seller')),
            ],
        ),
    ]
