# Generated by Django 3.0.8 on 2020-10-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_moneywithdrawl_sellertransc_tempaccountbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneywithdrawl',
            name='withdrawl_amount',
            field=models.IntegerField(null=True),
        ),
    ]
