# Generated by Django 3.0.8 on 2020-11-13 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20201110_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_system',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='unknown', max_length=40)),
                ('alert_text', models.CharField(default='There is no message here', max_length=300)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('alert_page', models.CharField(default='uknown', max_length=30)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Seller')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Customer')),
            ],
        ),
    ]
