# Generated by Django 3.0.8 on 2020-11-16 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20201114_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert_system',
            name='sender_status',
        ),
        migrations.CreateModel(
            name='Alert_order_customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_status', models.CharField(default='Uknown', max_length=40)),
                ('alert_text', models.CharField(default='Uknown', max_length=300)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Customer')),
            ],
        ),
    ]
