# Generated by Django 3.0.8 on 2020-11-16 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20201116_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alert_order_customer',
            new_name='Alert_system_customer',
        ),
    ]
