# Generated by Django 3.0.8 on 2020-11-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20201116_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert_system_customer',
            name='alert_page',
            field=models.CharField(default='Uknown', max_length=30),
        ),
    ]
