# Generated by Django 3.0.8 on 2020-11-16 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alert_system_customer_alert_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert_system_customer',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Order'),
        ),
    ]
