# Generated by Django 3.0.8 on 2020-11-16 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alert_system_customer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert_system',
            name='money_withdrawal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.MoneyWithdrawl'),
        ),
    ]
