# Generated by Django 3.0.8 on 2020-11-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20201117_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='store_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
