# Generated by Django 3.0.8 on 2020-11-17 01:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_auto_20201117_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='whatsapp_number',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='seller',
            name='store_email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='store_phone',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
    ]
