# Generated by Django 3.0.8 on 2020-11-20 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_auto_20201117_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='store_email',
        ),
    ]
