# Generated by Django 3.0.8 on 2020-11-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_auto_20201120_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
