# Generated by Django 3.0.8 on 2020-11-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_auto_20201122_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='seller',
            name='shipping_method',
            field=models.ManyToManyField(default='Uknown', to='store.ShipMethod'),
        ),
    ]
