# Generated by Django 3.0.8 on 2020-11-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_shipmethod_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
