# Generated by Django 3.0.8 on 2020-11-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_auto_20201126_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmethod',
            name='description',
            field=models.CharField(default='Unknown', max_length=600),
        ),
    ]
