# Generated by Django 3.0.8 on 2020-11-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_auto_20201129_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pop_count',
            field=models.IntegerField(default=0),
        ),
    ]
