# Generated by Django 3.0.8 on 2020-12-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_product_pop_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='seller',
            name='store_type',
            field=models.ManyToManyField(default='Uknown', to='store.StoreType'),
        ),
    ]
