# Generated by Django 3.0.8 on 2020-12-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_auto_20201201_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='store_whatsapp',
            field=models.CharField(default=0, max_length=11),
        ),
    ]
