# Generated by Django 3.0.8 on 2020-12-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_seller_store_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('whatsapp_number', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=60)),
                ('facebook', models.CharField(max_length=300)),
                ('instagram', models.CharField(max_length=300)),
            ],
        ),
    ]
