# Generated by Django 3.0.8 on 2020-12-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_admindetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetails',
            name='email',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='admindetails',
            name='facebook',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='admindetails',
            name='instagram',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='admindetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='admindetails',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
