# Generated by Django 3.0.8 on 2020-12-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_auto_20201201_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
