# Generated by Django 3.0.8 on 2020-12-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_workerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdetails',
            name='position',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
