# Generated by Django 3.0.8 on 2020-12-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_auto_20201201_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirm_payment',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
